name: Snyk Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk Test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --project-name=tarsilla-app/eslint-config --severity-threshold=high

      - name: Run Snyk Code Test
        uses: snyk/actions/node@master
        with:
          command: code test
          args: --project-name=tarsilla-app/eslint-config --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Monitor
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --project-name=tarsilla-app/eslint-config
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}